# Data analysis using python

## Q1 define low level language and high level language with 4 example
### ans Low level language:- they are close to machine code and are more difficult for humans to read and write.They provide little to no abstraction from the hardware
### High level language:- they are far from machine code and are easier for humans to read and write.They provide a lot of abstraction from the hardware
### example of low level language
#### 1. Assembly language
#### 2. C
#### 3. C++
#### 4. Fortran
### example of high level language
#### 1. Python
#### 2. Java
#### 3. C#
#### 4. JavaScript

## Q2 discuss various applications and features of python
### ans Python is a high-level, interpreted programming language that is widely used for various purposes such as
#### web development
#### scientific computing
#### data analysis
#### machine learning
### features of python
#### 1. Easy to learn and use
#### 2. High-level language
#### 3. Dynamic typing
#### 4. Object-oriented
#### 5. Extensive libraries and frameworks
#### 6. Cross-platform
#### 7. Large community

# Numpy library for array 

## --------------------------------------------------INTEGER------------------------------------------------------

In [75]:
import numpy as np
ar = np.array([1,2,3,4,5],int)
print(type(ar))
print(ar)

<class 'numpy.ndarray'>
[1 2 3 4 5]


## ---------------------------------------------------FLOAT--------------------------------------------------------

In [76]:
arr = np.array([1.4,2.0,3.23,4.5,5.7],float)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1.4  2.   3.23 4.5  5.7 ]


## ------------------------------------------------CHARACTER----------------------------------------------------

In [77]:
arr = np.array(['i','e','o'])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['i' 'e' 'o']


## ---------------------------------------------------STRING------------------------------------------------------

In [78]:
arr = np.array(["hi","hehe","hello"])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['hi' 'hehe' 'hello']


## -------------------------------------Accessing the function of 1-D array--------------------------------------
### 1 Modefying an element at a specific index
### 2 Determine characterstics of the array
#### 2.1 To identify size of array
#### 2.2 To identify data type of array
### 3 Mathematic function
#### 3.1 Sort the element of the array
#### 3.2 To identify power of all elements of array
#### 3.3 To identify squre root of all array element
#### 3.4 To identify absolute value of all array elements
### 4 Trigonometric function
#### 4.1 To identify sine of all array elements
#### 4.2 To identify cosine of all array elements
#### 4.3 To identify tangent of all array elements
### 5 Logrithmic/exponential function
#### 5.1 To identify log with exponential base of all array elements
#### 5.2 To identify log with base 10 of all array elements
#### 5.3 To identify exponential value of all array elements
### 6 Statistical function
#### 6.1 To identify main value of all elements of array
#### 6.2 To identify median value of all elements of array 
#### 6.3 To identify min value of all elements of array
#### 6.4 To identify max value of all elements of array
#### 6.5 To identify sum of all elements of array
#### 6.6 To identify product of all elements of array
## -------------------------------------------------PROGRAM-----------------------------------------------------

In [79]:
arr = np.array([1,2,3,4,5])
arr [3]=40
print("ANS:- ",arr)

ANS:-  [ 1  2  3 40  5]


In [80]:
arr = np.array([1,2,3,4,5])
arr [3]=40
print("ANS:- ",arr)
print("ANS:- ",arr.size)

ANS:-  [ 1  2  3 40  5]
ANS:-  5


In [81]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",arr.dtype)

ANS:-  [1 2 3 4 5]
ANS:-  int32


In [82]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.mean(arr))

ANS:-  [1 2 3 4 5]
ANS:-  3.0


In [83]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.median(arr))

ANS:-  [1 2 3 4 5]
ANS:-  3.0


In [84]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.min(arr))

ANS:-  [1 2 3 4 5]
ANS:-  1


In [85]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.max(arr))

ANS:-  [1 2 3 4 5]
ANS:-  5


In [86]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.sum(arr))

ANS:-  [1 2 3 4 5]
ANS:-  15


In [87]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.prod(arr))

ANS:-  [1 2 3 4 5]
ANS:-  120


In [88]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.sort(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [1 2 3 4 5]


In [89]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.power(arr,2))

ANS:-  [1 2 3 4 5]
ANS:-  [ 1  4  9 16 25]


In [90]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.sin(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [91]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.cos(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [92]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.tan(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [93]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.sqrt(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [1.         1.41421356 1.73205081 2.         2.23606798]


In [94]:
arr = np.array([1,2,3,4,5])
print("ANS:- ",arr)
print("ANS:- ",np.abs(arr))

ANS:-  [1 2 3 4 5]
ANS:-  [1 2 3 4 5]


In [95]:
a = np.array([1,2,3,4,5])
ar = np.array([6,7,8,9,10])
arr = a+ar
arra = ar-a
array = ar*a
arrays = ar/a
ar1 = ar%a
print("first array ",a)
print("second array ",ar)
print("addition of a and ar is ",arr)
print("subtraction of ar by a is ",arr)
print("multiplication of a and ar is ",arr)
print("division of ar by a is ",arr)
print("moduloses of ar by a is ",arr)

first array  [1 2 3 4 5]
second array  [ 6  7  8  9 10]
addition of a and ar is  [ 7  9 11 13 15]
subtraction of ar by a is  [ 7  9 11 13 15]
multiplication of a and ar is  [ 7  9 11 13 15]
division of ar by a is  [ 7  9 11 13 15]
moduloses of ar by a is  [ 7  9 11 13 15]


## Relational Operator
### > Greater than
### < Less than
### >= Greater than equal to
### <= Less than equal to
### == Equal to
### != Not equal to
## Logical Operator
### and && AND Logical 
### or || OR Logical 
### not ! NOT Logical 

## Truth table
### A truth table is a table that lists all possible combinations of inputs to a logical expression and the resulting

In [96]:
ar = np.array([11,20,33])
arr = np.array([12,20,30])
a1 = ar > arr
a2 = ar < arr
a3 = ar >= arr
a4 = ar <= arr
a5 = ar != arr
a6 = ar == arr
print("first array ", ar)
print("second array ", arr)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

first array  [11 20 33]
second array  [12 20 30]
[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
[ True False  True]
[False  True False]


# Multidimentional array

## ---------------------------------------------------Functions----------------------------------------------------

### Some function for 2d array are
#### Array()
#### matrix()
#### reshape()
#### 0's and 1's()

In [97]:
a = np.array([[100,200,300],[400,500,600],[700,800,900]])
print("2-D array is ")
print(a)

2-D array is 
[[100 200 300]
 [400 500 600]
 [700 800 900]]


In [98]:
a = np.matrix('100,200,300;400,500,600;700,800,900')
print("2-D array is ")
print(a)

2-D array is 
[[100 200 300]
 [400 500 600]
 [700 800 900]]


In [99]:
a = np.array([[100,200,300],[400,500,600]])
ar = np.reshape(a,(2,3))
print("2-D array is ")
print(a)

2-D array is 
[[100 200 300]
 [400 500 600]]


In [100]:
a = np.reshape((100,200,300,400,500,600),(3,2))
print("2-D array is ")
print(a)

2-D array is 
[[100 200]
 [300 400]
 [500 600]]


In [101]:
a = np.zeros((4,2))
print("2-D array is ")
print(a)

2-D array is 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [102]:
a = np.ones((4,2))
print("2-D array is ")
print(a)

2-D array is 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Slicing

In [103]:
# normal slice
a = np.reshape(range(100,500,20),(4,5))
print(a)
# slicing by only row indexes
print("First tow rows are : ",a[0:2])
# slicing by row and columns
print("First tow rows and first column are : ",a[0:2,0])
print("Second row and second to forth column : ",a[1,1:4])

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
First tow rows are :  [[100 120 140 160 180]
 [200 220 240 260 280]]
First tow rows and first column are :  [100 200]
Second row and second to forth column :  [220 240 260]


### Transpose

In [104]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(a.transpose())

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[[100 200 300 400]
 [120 220 320 420]
 [140 240 340 440]
 [160 260 360 460]
 [180 280 380 480]]


### Shape

In [105]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(a.shape)

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
(4, 5)


### Flatten

In [106]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(a.flatten())

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440
 460 480]


### Sort

In [107]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(np.sort(a))

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]


### Axis

In [108]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(np.sort(a,axis=0))
# axis =0 gives the default matrix
print(np.sort(a,axis=1))

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]


### Diagonal

In [109]:
a = np.reshape(range(100,500,20),(4,5))
print(a)
print(np.diagonal(a))

[[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
[100 220 340 460]
